apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      volumes:
      serviceAccountName: default
      containers:
        - name: go-prom-server
          image: whoabhisheksah/go-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: default
  labels:
    app: go-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:    
    app: go-server
  type: ClusterIP
